[2022-07-18 13:36:32,345] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_dag.transform manual__2022-07-18T13:36:23.526308+00:00 [queued]>
[2022-07-18 13:36:32,357] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_dag.transform manual__2022-07-18T13:36:23.526308+00:00 [queued]>
[2022-07-18 13:36:32,357] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-18 13:36:32,357] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-18 13:36:32,357] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-18 13:36:32,374] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transform> on 2022-07-18 13:36:23.526308+00:00
[2022-07-18 13:36:32,379] {standard_task_runner.py:52} INFO - Started process 2147 to run task
[2022-07-18 13:36:32,383] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'transform', 'manual__2022-07-18T13:36:23.526308+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp2znl0ext', '--error-file', '/tmp/tmp15_25h0p']
[2022-07-18 13:36:32,385] {standard_task_runner.py:80} INFO - Job 21: Subtask transform
[2022-07-18 13:36:32,455] {task_command.py:371} INFO - Running <TaskInstance: etl_dag.transform manual__2022-07-18T13:36:23.526308+00:00 [running]> on host 70b17816bd7e
[2022-07-18 13:36:32,541] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2022-07-18T13:36:23.526308+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-18T13:36:23.526308+00:00
[2022-07-18 13:36:32,552] {logging_mixin.py:115} INFO - [{'song_name': ['Avareh', 'Arezou', 'Tabiat', 'Setareh', 'Tasavor Kon', 'Daryaye Maghreb', 'Parandeh', 'Yadegari'], 'artist_name': ['Siavash Ghomayshi', 'Siavash Ghomayshi', 'Siavash Ghomayshi', 'Siavash Ghomayshi', 'Siavash Ghomayshi', 'Siavash Ghomayshi', 'Siavash Ghomayshi', 'Siavash Ghomayshi'], 'played_at': ['2022-07-18T05:48:12.234Z', '2022-07-17T20:44:56.091Z', '2022-07-17T20:41:01.954Z', '2022-07-17T20:37:43.707Z', '2022-07-17T20:34:02.940Z', '2022-07-17T20:29:53.538Z', '2022-07-17T20:25:50.882Z', '2022-07-17T20:22:27.220Z'], 'timestamp': ['2022-07-18', '2022-07-17', '2022-07-17', '2022-07-17', '2022-07-17', '2022-07-17', '2022-07-17', '2022-07-17']}]
[2022-07-18 13:36:32,569] {logging_mixin.py:115} INFO -                                            song_name  ...                                          timestamp
0  [Avareh, Arezou, Tabiat, Setareh, Tasavor Kon,...  ...  [2022-07-18, 2022-07-17, 2022-07-17, 2022-07-1...

[1 rows x 4 columns]
[2022-07-18 13:36:32,569] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 92, in transform
    if check_if_valid_data(song_df):
  File "/opt/airflow/dags/etl_dag.py", line 26, in check_if_valid_data
    if pd.Series(df['played_at']).is_unique:
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/base.py", line 1031, in is_unique
    return self.nunique(dropna=False) == len(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/base.py", line 1017, in nunique
    uniqs = self.unique()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 2039, in unique
    return super().unique()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/base.py", line 979, in unique
    result = unique1d(values)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/algorithms.py", line 431, in unique
    uniques = table.unique(values)
  File "pandas/_libs/hashtable_class_helper.pxi", line 5363, in pandas._libs.hashtable.PyObjectHashTable.unique
  File "pandas/_libs/hashtable_class_helper.pxi", line 5310, in pandas._libs.hashtable.PyObjectHashTable._unique
TypeError: unhashable type: 'list'
[2022-07-18 13:36:32,580] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=transform, execution_date=20220718T133623, start_date=20220718T133632, end_date=20220718T133632
[2022-07-18 13:36:32,594] {standard_task_runner.py:97} ERROR - Failed to execute job 21 for task transform (unhashable type: 'list'; 2147)
[2022-07-18 13:36:32,634] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-18 13:36:32,699] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
