[2022-07-16 15:32:42,125] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2022-07-15T00:00:00+00:00 [queued]>
[2022-07-16 15:32:42,174] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2022-07-15T00:00:00+00:00 [queued]>
[2022-07-16 15:32:42,174] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 15:32:42,175] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-16 15:32:42,175] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 15:32:42,230] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): accurate> on 2022-07-15 00:00:00+00:00
[2022-07-16 15:32:42,237] {standard_task_runner.py:52} INFO - Started process 1741 to run task
[2022-07-16 15:32:42,243] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'scheduled__2022-07-15T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpiahk9sxh', '--error-file', '/tmp/tmpb995strt']
[2022-07-16 15:32:42,243] {standard_task_runner.py:80} INFO - Job 42: Subtask accurate
[2022-07-16 15:32:42,370] {task_command.py:371} INFO - Running <TaskInstance: my_dag.accurate scheduled__2022-07-15T00:00:00+00:00 [running]> on host f32a6ddd91ec
[2022-07-16 15:32:42,624] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=accurate
AIRFLOW_CTX_EXECUTION_DATE=2022-07-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-15T00:00:00+00:00
[2022-07-16 15:32:42,627] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-16 15:32:42,628] {subprocess.py:74} INFO - Running command: ['bash', '-c', " echo 'accurate'"]
[2022-07-16 15:32:42,651] {subprocess.py:85} INFO - Output:
[2022-07-16 15:32:42,656] {subprocess.py:92} INFO - accurate
[2022-07-16 15:32:42,657] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-16 15:32:42,748] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, execution_date=20220715T000000, start_date=20220716T153242, end_date=20220716T153242
[2022-07-16 15:32:42,817] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-16 15:32:42,924] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
